{{- if $.Values.cron.jobs }}
{{- range $cronkey, $cronvalue := $.Values.cron.jobs }}
{{- if $cronvalue.enabled }}
{{- if semverCompare ">=1.21-0" $.Capabilities.KubeVersion.GitVersion -}}
apiVersion: batch/v1
{{- else -}}
apiVersion: batch/v1beta1
{{- end }}
kind: CronJob
metadata:
  {{- $nameMaxLength := len $cronkey | sub 51 | int }}
  name: {{ include "wordpress-bedrock.fullname" $ | trunc $nameMaxLength }}-{{ $cronkey }}
  labels:
{{ include "wordpress-bedrock.labels" $ | indent 4 }}
  annotations:
    {{- if $.Values.wordpress.uptime }}
    downscaler/uptime: {{ $.Values.wordpress.uptime }}
    {{- end }}
    checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
spec:
  {{- $schedule := dig "schedule" "" $cronvalue }}
  {{- $scheduleEveryXHr := dig "scheduleEveryXHr" "" $cronvalue }}
  {{- $scheduleEveryXMin := dig "scheduleEveryXMin" "" $cronvalue }}
  {{- $scheduleOnDay := dig "scheduleOnDay" "*" $cronvalue }}
  {{- if $schedule }}
  schedule: "{{ $schedule }}"
  {{- else if $scheduleEveryXHr }}
  {{- if ( and ( eq ( mod 24 $scheduleEveryXHr ) 0 ) ( not ( eq ( int $scheduleEveryXHr ) 24 ) ) ) }}
  schedule: "0 {{ mod ( randNumeric 2 | atoi ) $scheduleEveryXHr }}-23/{{ $scheduleEveryXHr }} * * {{ $scheduleOnDay }}"
  {{- end }}
  {{- else if $scheduleEveryXMin }}
  {{- if ( and ( eq ( mod 60 $scheduleEveryXMin ) 0 ) ( not ( eq ( int $scheduleEveryXMin ) 60 ) ) ) }}
  schedule: "{{ mod ( randNumeric 2 | atoi ) $scheduleEveryXMin }}-59/{{ $scheduleEveryXMin }} * * * {{ $scheduleOnDay }}"
  {{- end }}
  {{- end }}
  concurrencyPolicy: {{ $cronvalue.concurrencyPolicy | default "Forbid" }}
  {{- if $cronvalue.startingDeadlineSeconds }}
  startingDeadlineSeconds: {{ $cronvalue.startingDeadlineSeconds }}
  {{- end }}
  jobTemplate:
    spec:
      backoffLimit: {{ $cronvalue.backoffLimit | default 0 }}
      template:
        metadata:
          labels:
            {{- include "wordpress-bedrock.selectorLabels" $ | nindent 12 }}
            app.kubernetes.io/component: "cronjob"
          {{- with $.Values.podLabels }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
          annotations:
            checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") $ | sha256sum }}
          {{- with $.Values.podAnnotations }}
            {{- toYaml . | nindent 12 }}
          {{- end }}
            karpenter.sh/do-not-evict: "true"
        spec:
        {{- with $.Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
        {{- end }}
          priorityClassName: background
          serviceAccountName: {{ template "wordpress-bedrock.serviceAccountName" $ }}
          securityContext:
            {{- toYaml $.Values.podSecurityContext | nindent 12 }}
          containers:
          - name: wordpress-cron
            securityContext:
            {{- toYaml $.Values.php.securityContext | nindent 14 }}
            image: "{{ $.Values.php.image.repository }}:{{ $.Values.php.image.tag }}"
            imagePullPolicy: {{ $.Values.php.image.pullPolicy }}
            workingDir: /app
            command:
            - {{ $cronvalue.command }}
            env:
              - name: AWS_ZONE
                valueFrom:
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.labels['topology.kubernetes.io/zone']
            {{- if $.Values.offload.bucket }}
              - name: WP_OFFLOAD_BUCKET
                value: {{ $.Values.offload.bucket | quote }}
              - name: WP_OFFLOAD_REGION
                value: {{ $.Values.offload.region | quote }}
              - name: WP_OFFLOAD_DOMAIN
                value: {{ $.Values.offload.domain | quote }}
              - name: WP_OFFLOAD_CLOUDFRONT
                value: {{ $.Values.offload.cloudfront | quote }}
              - name: WP_OFFLOAD_LOCAL_DOMAINS
                value: {{ $.Values.offload.local_domains | quote }}
          {{- end }}
              - name: WP_DEFAULT_HOST
                value: {{ index $.Values.ingress.hosts 0 "host" | quote }}
              - name: WP_PLUGINS
                value: {{ join " " $.Values.plugins | quote }}
          {{- range $key, $value := $.Values.externalSecrets.mapping }}
              {{- if not (contains "wordpress-" $key) }}
              {{- if not (contains "-root-" $key) }}
              - name: {{ $key | upper | replace "-" "_" }}
                valueFrom:
                  secretKeyRef:
                    name: {{ template "wordpress-bedrock.fullname" $ }}
                    key: {{ $key }}
              {{- end }}
              {{- end }}
          {{- end }}
      {{- if $.Values.extraEnv }}
{{ toYaml $.Values.extraEnv | indent 14 }}
      {{- end }}
            volumeMounts:
            - mountPath: /usr/local/etc/php/conf.d/cron.ini
              name: config-volume
              subPath: {{ $cronkey }}.ini
              readOnly: true
            - name: tmp-volume
              mountPath: /tmp
              readOnly: false
{{- if $.Values.efs.enabled }}
            - name: efs
              mountPath: /var/www/html/web/{{ $.Values.efs.mountPath }}
              readOnly: false
{{- end }}
            resources:
              {{- if $cronvalue.resources }}
              {{- toYaml $cronvalue.resources | nindent 14 }}
              {{- else }}
              {{- toYaml $.Values.cron.resources | nindent 14 }}
              {{- end }}
          restartPolicy: {{ $cronvalue.restartPolicy | default "Never" }}
          nodeSelector:
            {{- if $cronvalue.nodeSelector }}
            {{- toYaml $cronvalue.nodeSelector | nindent 12 }}
            {{- else }}
            {{- toYaml $.Values.cron.nodeSelector | nindent 12 }}
            {{- end }}
          tolerations:
            {{- if $cronvalue.tolerations }}
            {{- toYaml $cronvalue.tolerations | nindent 12 }}
            {{- else }}
            {{- toYaml $.Values.cron.tolerations | nindent 12 }}
            {{- end }}
          volumes:
          - name: config-volume
            configMap:
              # Provide the name of the ConfigMap containing the files you want
              # to add to the container
              name: {{ include "wordpress-bedrock.fullname" $ }}
          - name: tmp-volume
            emptyDir: {}
{{- if $.Values.efs.enabled }}
          - name: efs
            nfs:
              path: /{{ $.Values.efs.subPath }}
              server: {{ $.Values.efs.fsid }}.efs.{{ $.Values.efs.awsRegion }}.amazonaws.com
{{- end }}
---
{{- end }}
{{- end }}
{{- end }}
