apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "wordpress-bedrock.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "wordpress-bedrock.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- if .Values.podAnnotations }}
        ## Custom pod annotations
        {{- range $key, $value := .Values.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
        {{- end }}
    spec:
    {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      serviceAccountName: {{ template "wordpress-bedrock.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: copy-files
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          command: ['sh', '-c', 'cp -r /app/* /var/www/html']
          volumeMounts:
          - name: web-volume
            mountPath: /var/www/html
      containers:
        - name: {{ .Chart.Name }}-nginx
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.nginx.image.repository }}:{{ .Values.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.nginx.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /wp/wp-login.php
              port: http
          readinessProbe:
            httpGet:
              path: /wp/wp-login.php
              port: http
          volumeMounts:
          - mountPath: /etc/nginx/conf.d/default.conf
            name: config-volume
            subPath: nginx-default.conf
          - name: web-volume
            mountPath: /var/www/html
          resources:
            {{- toYaml .Values.nginx.resources | nindent 12 }}
        - name: {{ .Chart.Name }}-php-fpm
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.php.image.repository }}:{{ .Values.php.image.tag }}"
          imagePullPolicy: {{ .Values.php.image.pullPolicy }}
          ports:
            - name: fpm
              containerPort: 9000
              protocol: TCP
          volumeMounts:
          - mountPath: /usr/local/etc/php-fpm.conf
            name: config-volume
            subPath: php-fpm.conf
          - mountPath: /usr/local/etc/php-fpm.d/www.conf
            name: config-volume
            subPath: www.conf
          - name: web-volume
            mountPath: /var/www/html
          env:
          {{ if $.Values.offload.bucket }}
            - name: WP_OFFLOAD_BUCKET
              value: {{ $.Values.offload.bucket | quote }}
            - name: WP_OFFLOAD_REGION
              value: {{ $.Values.offload.region | quote }}
            - name: WP_OFFLOAD_DOMAIN
              value: {{ $.Values.offload.domain | quote }}
            - name: WP_OFFLOAD_CLOUDFRONT
              value: {{ $.Values.offload.cloudfront | quote }}
          {{- end }}
            - name: WP_DEFAULT_HOST
              value: {{ index $.Values.ingress.hosts 0 "host" | quote }}
            - name: WP_PLUGINS
              value: {{ join " " $.Values.plugins | quote }}
        {{- range $key, $value := .Values.externalSecrets.mapping }}
            {{ if not (contains "wordpress-" $key) }}
            {{ if not (contains "-root-" $key) }}
            - name: {{ $key | upper | replace "-" "_" }}
              valueFrom:
                secretKeyRef:
                  name: {{ template "wordpress-bedrock.fullname" $ }}
                  key: {{ $key }}
            {{- end }}
            {{- end }}
        {{- end }}
      {{- if .Values.extraEnv }}
{{ toYaml .Values.extraEnv | indent 12 }}
      {{- end }}
          resources:
            {{- toYaml .Values.php.resources | nindent 12 }}
{{- if ( .Values.monitoring.enabled ) }}
        - name: {{ .Chart.Name }}-php-fpm-monitor
          image: "{{ .Values.exporter.phpfpm.image.repository }}:{{ .Values.exporter.phpfpm.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.phpfpm.image.pullPolicy }}
          env:
          - name: PHP_FPM_WEB_LISTEN_ADDRESS
            value: ":{{ .Values.exporter.phpfpm.port }}"
          - name: PHP_FPM_WEB_TELEMETRY_PATH
            value: {{ .Values.exporter.phpfpm.metrics | quote }}
          - name: PHP_FPM_SCRAPE_URI
            value: {{ .Values.exporter.phpfpm.scrape_uri | quote }}
          - name: PHP_FPM_FIX_PROCESS_COUNT
            value: {{ .Values.exporter.phpfpm.fix_process_count | quote }}
          - name: PHP_FPM_LOG_LEVEL
            value: {{ .Values.exporter.phpfpm.log_level | quote }}
          ports:
            - name: php-fpm-metrics
              containerPort: {{ .Values.exporter.phpfpm.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: php-fpm-metrics
          resources:
{{ toYaml .Values.exporter.phpfpm.resources | indent 12 }}
        - name: {{ .Chart.Name }}-nginx-monitor
          image: "{{ .Values.exporter.nginx.image.repository }}:{{ .Values.exporter.nginx.image.tag }}"
          imagePullPolicy: {{ .Values.exporter.nginx.image.pullPolicy }}
          env:
          - name: LISTEN_ADDRESS
            value: ":{{ .Values.exporter.nginx.port }}"
          - name: TELEMETRY_PATH
            value: {{ .Values.exporter.nginx.telemetry_path | quote }}
          - name: NGINX_PLUS
            value: {{ .Values.exporter.nginx.nginx_plus | quote }}
          - name: SCRAPE_URI
            value: {{ .Values.exporter.nginx.scrape_uri | quote }}
          - name: SSL_VERIFY
            value: {{ .Values.exporter.nginx.ssl_verify | quote }}
          - name: TIMEOUT
            value: {{ .Values.exporter.nginx.timeout | quote }}
          - name: NGINX_RETRIES
            value: {{ .Values.exporter.nginx.nginx_retries | quote }}
          - name: NGINX_RETRY_INTERVAL
            value: {{ .Values.exporter.nginx.nginx_retry_interval | quote }}
          ports:
            - name: nginx-metrics
              containerPort: {{ .Values.exporter.nginx.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: nginx-metrics
          resources:
{{ toYaml .Values.exporter.nginx.resources | indent 12 }}
{{ end }}
      volumes:
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{ include "wordpress-bedrock.fullname" . }}
      - name: web-volume
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
