{{- if $.Values.hooks }}
{{- range $hooktype, $hookvalue := $.Values.hooks }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-{{ $hooktype }}-hook
  labels:
{{ include "wordpress-bedrock.labels" $ | indent 4 }}
    app.kubernetes.io/component: "hook"
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "3"
    "helm.sh/hook": {{ $hooktype }}
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      labels:
        {{- include "wordpress-bedrock.selectorLabels" $ | nindent 8 }}
        app.kubernetes.io/component: "hook"
      {{- with $.Values.podLabels }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      annotations:
      {{- with $.Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
        karpenter.sh/do-not-evict: "true"
    spec:
    {{- with $.Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
    {{- end }}
      containers:
      - name: job-done
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
        image: public.ecr.aws/runecast/busybox:1.33.1
        command: ['sh', '-c', 'echo "all jobs completed"']
      initContainers:
      {{- if $hookvalue }}
      {{- range $hookname := $hookvalue }}
      - name: {{ $hookname }}
        image: "{{ $.Values.php.image.repository }}:{{ $.Values.php.image.tag }}"
        imagePullPolicy: {{ $.Values.php.image.pullPolicy }}
        workingDir: /app
        command:
        - /scripts/{{ $hookname }}.sh
        env:
        - name: AWS_ZONE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.labels['topology.kubernetes.io/zone']
        {{- if $.Values.offload.bucket }}
        - name: WP_OFFLOAD_BUCKET
          value: {{ $.Values.offload.bucket | quote }}
        - name: WP_OFFLOAD_REGION
          value: {{ $.Values.offload.region | quote }}
        - name: WP_OFFLOAD_DOMAIN
          value: {{ $.Values.offload.domain | quote }}
        - name: WP_OFFLOAD_CLOUDFRONT
          value: {{ $.Values.offload.cloudfront | quote }}
        - name: WP_OFFLOAD_LOCAL_DOMAINS
          value: {{ $.Values.offload.local_domains | quote }}
        {{- end }}
        - name: WP_DEFAULT_HOST
          value: {{ index $.Values.ingress.hosts 0 "host" | quote }}
        - name: WP_PLUGINS
          value: {{ join " " $.Values.plugins | quote }}
        {{- range $key, $value := $.Values.externalSecrets.env }}
        - name: {{ $key }}
          valueFrom:
            secretKeyRef:
              name: {{ template "wordpress-bedrock.fullname" $ }}
              key: {{ $key | lower | replace "_" "-" }}
        {{- end }}
        {{- with $.Values.env }}
        {{- range $key, $value := . }}
        - name: {{ $key }}
          value: {{ $value | quote }}
        {{- end }}
        {{- end }}
        volumeMounts:
          - mountPath: /etc/php/7.2/fpm/php-fpm.conf
            name: config-volume
            subPath: fpm.conf
            readOnly: true
          - mountPath: /tmp
            name: tmp-volume
      {{- end }}
      {{- end }}
      restartPolicy: Never
      volumes:
      - name: tmp-volume
        emptyDir: {}
      - name: config-volume
        configMap:
          # Provide the name of the ConfigMap containing the files you want
          # to add to the container
          name: {{ template "wordpress-bedrock.fullname" $ }}
  backoffLimit: 1
---
{{- end }}
{{- end }}
