{{- if and .Values.hpa .Values.hpa.enabled .Values.hpa.httpAddon (not .Values.hpa.httpAddon.enabled) }}
{{- if eq .Values.hpa.engine "keda" }}

apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
  annotations:
    {{- if .Values.wordpress.uptime }}
    downscaler/uptime: {{.Values.wordpress.uptime}}
    {{- end }}
spec:
  scaleTargetRef:
    name: {{ include "wordpress-bedrock.fullname" . }}-worker
  pollingInterval: 30
  cooldownPeriod:  300
  minReplicaCount: {{ .Values.replicaCount }}
  maxReplicaCount: {{ .Values.hpa.maxReplicas }}
  triggers:
  - type: cpu
    metadata:
      type: Utilization
      value: "{{ .Values.hpa.targets.cpu }}"
  {{- if .Values.hpa.targets.memory }}
  - type: memory
    metadata:
      type: Utilization
      value: "{{ .Values.hpa.targets.memory }}"
  {{- end }}
  - type: prometheus
    metadata:
      serverAddress: "{{ .Values.hpa.prometheus.serverAddress }}"
      metricName: phpfpm_active_processes
      threshold: '{{ .Values.hpa.targets.php }}'
      query: sum(phpfpm_active_processes{service="{{ include "wordpress-bedrock.fullname" . }}-worker",namespace="{{ .Release.Namespace }}"})
  - type: prometheus
    metadata:
      serverAddress: "{{ .Values.hpa.prometheus.serverAddress }}"
      metricName: nginx_connections_active
      threshold: '{{ .Values.hpa.targets.nginx }}'
      query: sum(nginx_connections_active{service="{{ include "wordpress-bedrock.fullname" . }}-worker",namespace="{{ .Release.Namespace }}"})
{{- end }}
{{- end }}
