{{- if gt .Values.replicaCount 1.0 -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
spec:
  minAvailable: 1
  selector:
    matchLabels:
      {{- include "wordpress-bedrock.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: "worker"
{{- end -}}