{{- if .Values.externalSecrets.enabled }}
{{- if eq .Values.externalSecrets.engine "kube-external-secrets" }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
secretDescriptor:
  backendType: {{ .Values.externalSecrets.backendType }}
  data:
  {{- range $key, $value := .Values.externalSecrets.mapping }}
    - key: {{ $value }}
      name: {{ $key }}
  {{- end }}
{{- end }}
{{- if eq .Values.externalSecrets.engine "external-secrets" }}
---
apiVersion: external-secrets.io/v1alpha1
kind: SecretStore
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
spec:
  provider:
    aws:
      service: ParameterStore
      region: {{ .Values.externalSecrets.region }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: example
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: {{ include "wordpress-bedrock.fullname" . }}
    kind: SecretStore
  target:
    name: {{ include "wordpress-bedrock.fullname" . }}
    creationPolicy: Owner
  data:
  {{- range $key, $value := .Values.externalSecrets.mapping }}
    - secretKey: {{ $value }}
      remoteRef:
        key: {{ $key }}
  {{- end }}
{{- end }}
{{- end }}
