{{- if .Values.externalSecrets.enabled }}
apiVersion: 'kubernetes-client.io/v1'
kind: ExternalSecret
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "0"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
secretDescriptor:
  backendType: {{ .Values.externalSecrets.backendType }}
  data:
  {{- range $key, $value := .Values.externalSecrets.mapping }}
    - key: {{ $value }}
      name: {{ $key }}
  {{- end }}
{{- end }}