{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "wordpress-bedrock.serviceAccountName" . }}
{{- if .Values.serviceAccount.iamRoleArn }}
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.serviceAccount.iamRoleArn }}
{{- end }}
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
{{- end -}}
