apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}-worker
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
    app.kubernetes.io/component: "worker"
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if ( .Values.monitoring.enabled ) }}
    - port: {{ .Values.exporter.nginx.port }}
      targetPort: nginx-metrics
      protocol: TCP
      name: nginx-metrics
    - port: {{ .Values.exporter.phpfpm.port }}
      targetPort: php-fpm-metrics
      protocol: TCP
      name: php-fpm-metrics
{{ end }}
  selector:
    {{- include "wordpress-bedrock.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: "worker"
