apiVersion: v1
kind: Service
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
{{- if ( .Values.monitoring.enabled ) }}
    - port: {{ .Values.exporter.nginx.port }}
      targetPort: nginx-metrics
      protocol: TCP
      name: nginx-metrics
    - port: {{ .Values.exporter.phpfpm.port }}
      targetPort: php-fpm-metrics
      protocol: TCP
      name: php-fpm-metrics
{{ end }}
  selector:
    app.kubernetes.io/name: {{ include "wordpress-bedrock.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
