{{- if .Values.externalSecrets.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}-wait-hook-sa
  namespace: {{ $.Release.Namespace }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}-wait-hook-role
  namespace: {{ $.Release.Namespace }}
rules:
  - apiGroups: ["external-secrets.io"]
    resources: ["externalsecrets"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}-wait-hook-rb
  namespace: {{ $.Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ include "wordpress-bedrock.fullname" . }}-wait-hook-sa
    namespace: {{ $.Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "wordpress-bedrock.fullname" . }}-wait-hook-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "wordpress-bedrock.fullname" . }}-wait-hook
  namespace: {{ $.Release.Namespace }}
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  ttlSecondsAfterFinished: 600
  template:
    metadata:
      annotations:
        karpenter.sh/do-not-evict: "true"
    spec:
      containers:
      - name: job-done
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
        image: ghcr.io/arvatoaws-labs/docker-external-secrets-helper:latest
        imagePullPolicy: IfNotPresent
        command:
          - "wait.sh"
        env:
          - name: NAMESPACE
            value: {{ $.Release.Namespace }}
          - name: EXTERNALSECRET
            value: {{ include "wordpress-bedrock.fullname" . }}
      restartPolicy: Never
      serviceAccountName: {{ include "wordpress-bedrock.fullname" . }}-wait-hook-sa
{{- end }}
