{{- if .Values.externalSecrets.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ $.Release.Name }}-pre-install-wait-hook
  labels:
{{ include "wordpress-bedrock.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook-weight": "1"
    "helm.sh/hook": pre-install
    "helm.sh/hook-delete-policy": hook-succeeded,before-hook-creation
spec:
  ttlSecondsAfterFinished: 600
  template:
    spec:
      metadata:
        annotations:
          karpenter.sh/do-not-evict: "true"
      containers:
      - name: job-done
        securityContext:
          capabilities:
            drop:
            - ALL
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 65534
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
        image: public.ecr.aws/runecast/busybox:1.33.1
        command: ['sh', '-c', 'sleep 60']
      restartPolicy: Never
{{- end }}
