name: Validate

on:
  #push:
  #  branches:
  #    - master
  #    - develop
  pull_request:
    branches:
      - master
      - develop
  workflow_dispatch:
  workflow_call:

jobs:
  verify-chart:
    runs-on: arvato

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v7

    - name: Set up Helm
      uses: azure/setup-helm@v5
      with:
        version: 'v4.2.4'

    - name: Run helm show chart
      run: |
        helm show chart .

    - name: Run helm lint
      run: |
        helm lint .

    - name: Run helm template
      run: |
        helm template .

    - name: Run helm template with test values
      run: |
        helm template . -f ./values_test.yaml